/**************************************************************************************
Apex Class Name     : PC_Conditional_Bldr_Controller
Description         : This class is used for testing PC_Conditional_Bldr_Controller;
CreatedBy           : Deloitte
Created Date        : 22 Jun 2018
Modification Log    :
--------------------------------------------------------------------------------------------------------------
Developer                   Date                   Description
----------------------------------------------------------------------------
Vivek Kumar Mishra         22 Jun 2018            Initial version
Vivek Kumar Mishra         28 Jun 2018            Added testGetFieldPicklistValue method
Kanteti Kishore            27 Mar 2020            Added testGetTriggerObjectLookUpFields method
Kanteti Kishore            27 Jul 2020            [PC-6494]Modified testGetAllPicklistValue method
Kanteti Kishore            14 Apr 2021            [PC-7009]PC_Conditional_Bldr_Controller is deprecated
                                                    Removed all test methods
*****************************************************************************************/
@isTest
public with sharing class PC_Test_Conditional_Bldr_Controller {
    //Class deprecated. Instead of this class we are currently using PC_PropertiesAndConditionsBuilder.
}