/*********************************************************************************************************
Class Name      : PC_Test_UBC_PBMSWrapper
Description     : Test class for PC_UBC_PBMSWrapper - Wrapper Class for UBC Pharmacy Card Lookup Service
Created By      : Vijay Kashikar
Created Date    : Mar 28, 2018
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                           Description
-----------------------------------------------------------------------------------------------------
Vijay Kashikar              Mar 28, 2017                Initial Version
*********************************************************************************************************/

@IsTest
private class PC_Test_UBC_PBMSWrapper {
    /*static testMethod void testBehavior() {
        PC_UBC_PBMSWrapper pbmsWrapper = new PC_UBC_PBMSWrapper();
        pbmsWrapper.id = '';
        pbmsWrapper.pbmStatusMessage = '';
        pbmsWrapper.name = '';
        List<PC_UBC_PBMSWrapper.plan> plans = new List<PC_UBC_PBMSWrapper.plan>();
        PC_UBC_PBMSWrapper.plan plan = new PC_UBC_PBMSWrapper.plan();
        plan.name = '';
        plan.id = '';
        plan.isPriorAuthorizationRequired = false;


        List<PC_UBC_PBMSWrapper.outOfPocketRange> outOfPocketRanges = new List<PC_UBC_PBMSWrapper.outOfPocketRange>();
        PC_UBC_PBMSWrapper.outOfPocketRange outOfPocketRange = new PC_UBC_PBMSWrapper.outOfPocketRange();
        outOfPocketRanges.add(outOfPocketRange);
        plan.outOfPocketRanges = outOfPocketRanges;

        List<PC_UBC_PBMSWrapper.coverage> coverages = new List<PC_UBC_PBMSWrapper.coverage>();
        PC_UBC_PBMSWrapper.coverage cov = new PC_UBC_PBMSWrapper.coverage();
        cov.id = '';
        cov.isCovered = false;
        cov.pharmacyType = '';
        coverages.add(cov);
        plan.coverage = coverages;

        PC_UBC_PBMSWrapper.insurance insurance = new PC_UBC_PBMSWrapper.insurance();
        insurance.id = '';
        insurance.pcn = '';
        insurance.bin = '';
        insurance.familyUnitNumber = '';
        insurance.isEsi = false;
        insurance.participantId = '';
        insurance.planNumber = '';
        insurance.policyId = '';

        PC_UBC_PBMSWrapper.insuranceGroup insuranceGroup = new PC_UBC_PBMSWrapper.insuranceGroup();
        insuranceGroup.id = '';
        insuranceGroup.name = '';
        insuranceGroup.groupId = '';

        insurance.insuranceGroup = insuranceGroup;

        plan.insurance = insurance;


        PC_UBC_PBMSWrapper.memberInfo memberInfo = new PC_UBC_PBMSWrapper.memberInfo();
        memberInfo.id = '';
        memberInfo.gender = '';
        memberInfo.birthdate = '';
        memberInfo.firstName = '';
        memberInfo.changeFlag =false;
        memberInfo.lastName = '';
        memberInfo.memberId = '';
        memberInfo.relationship = '';

        PC_UBC_PBMSWrapper.memberAddress memberAddress = new PC_UBC_PBMSWrapper.memberAddress();
        memberAddress.id = '';
        memberAddress.addressOne = '';
        memberAddress.city = '';
        memberAddress.postalCode = '';
        memberAddress.state = '';
        memberAddress.type = '';

        memberInfo.address = memberAddress;
        plan.memberInfo = memberInfo;
        plans.add(plan);

        pbmsWrapper.plans = plans;



    }*/
}